ignore:
  - "tests"
  - "daceml/testing"
  - "daceml/onnx/shape_inference/symbolic_shape_infer.py"

coverage:
  range: 40..90
  round: nearest
  status:
    patch: off
    project:
      default:
        threshold: 2%
